import "./globals.css";
import type { Metadata } from "next";
import Header from "@src/components/header";
import HeaderMobile from "@src/components/header-mobile";
import SideNav from "@src/components/side-nav";
import PageWrapper from "@src/components/page-wrapper";
import MarginWidthWrapper from "@src/components/margin-width-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white">
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header />
              <HeaderMobile />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
